### ISSUE TITLE
getSSIDNetworkID, getConnectedNetworkID, getConnectedSSID, getConnectedBSSID don't need to be async

### ISSUE THREAD

**Issue by gregoiregentil** [tripflex/WifiWizard2#14]
On version 3.0.0 all the functions listed in the title of this issue are async. Android returns those functions immediately so there is no need to have them async in the plugin. wifiwizard and wifiwizard 2.x can return the results immediately.

**Comment by tripflex** [comment]
While yes that may be true for Android, that's not the case for Cordova plugins, as the `exec` call is made async and requires callbacks ... that's why instead of using a bunch of callbacks, they are handled by promises.

**Comment by gregoiregentil** [comment]
I don't understand well your comment. If it's true for Android, how can not it be the case for Cordova? The point of this issue which you already closed is to highlight that it's better to be as close as possible how WifiWizard version 1 works in order to keep backward compatibility with as much code as possible. The async architecture for something that doesn't require it to be, adds a lot of complexity how to process the result of the call.

**Comment by tripflex** [comment]
@gregoiregentil when a cordova call is made to execute something (either in Android or iOS) the `exec` method is called, which requires a success callback and a failure callback:
https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/#sample-javascript

The version 2.1.x of this plugin still has the same methods as the original version 1, although I did add async ones, but to call those you have to add `async` to method .. ie `getConnectedSSIDAsync` ... the `getConnectedSSID` is the exact same as version 1

https://github.com/tripflex/WifiWizard2/tree/2.1.x

But even with those, because it requires callbacks it's still not returning a value from the javascript method called `getConnectedSSID` and is why you have to specify either a function to be called, or an anonymous function we may be the part where you're getting confused:

So while yes I absolutely agree that if it it wasn't necessary I wouldn't have used it that way, but the I chose lesser of two evils ... callbacks or promises ... I choose promises all day long

```js
WifiWizard2.getConnectedSSID( 
    function( result ){ 
        console.log( 'success' ); 
    },
    function( error ){
        console.log( 'fail' );
    }
);
```

Whereas with using promises if it's inside an async function you can do just this:

```js
async function doSomething(){
    let SSID = await WifiWizard2.getConnectedSSID();
}
```

or in standard function just use `.then`:
```js
WifiWizard2.getConnectedSSID().then( function( ssid ){
    console.log( 'SSID: ' + ssid );
});
```

You can see examples in my demo meteor app:
https://github.com/tripflex/WifiWizard2Demo/blob/master/client/views/home/home.js#L87

**Comment by gregoiregentil** [comment]
I understand your point and your choice - not going my way, but I get it.

In the end, I didn't use WiFiWizard2 because it was not API to API compatible and essentially because my main problem (issue #13) was the same on both WiFiWizard and WiFiWizard2.
