### ISSUE TITLE
t I can not connect to open wifis networks. Install version 3.

### ISSUE THREAD

**Issue by Hippoi** [tripflex/WifiWizard2#15]
Hi, I have version 2.1.1 in my project, it works fine, but I can not connect to open wifis networks, that is, without a password. Since I have no error information, I want to install version 3.0 but I do not know how to do it.

Can you help me?

Thank you

**Comment by Pietfro** [comment]
cordova plugin add https://github.com/tripflex/wifiwizard2.git#3.0.0

**Comment by Hippoi** [comment]
Solution

For wifi WAP:
           wifiConfig = WifiWizard2.formatWPAConfig(mySSID, myPassword);
            WifiWizard2.addNetwork(wifiConfig,......

For open wifi:
            wifiConfig = WifiWizard2.formatWifiConfig(mySSID, "");
            WifiWizard2.addNetwork(wifiConfig,......

**Comment by tripflex** [comment]
@Hippoi hmm that's weird, because the code should return the config as none when the password and algorithm are empty:

https://github.com/tripflex/WifiWizard2/blob/master/www/WifiWizard2.js#L87-L120

In 3.0.0 you just use the `connect` and it's no longer necessary to format config first, thanks for the update on this though

**Comment by danielavrella** [comment]
@Hippoi and @tripflex does that work for iOS?
I'm using 3.0 and all I get is the "NEHotspotConfiguration invalid WPA/WPA2 passphrase length" error when running on my device.

Current code is:
WifiWizard2.iOSConnectNetwork('my_wifi_name', '');

**Comment by gailu** [comment]
@danielavrella
I am facing same problem it does not work on ios for open networks
