### ISSUE TITLE
Be more precise in README file

### ISSUE THREAD

**Issue by touficbatache** [tripflex/WifiWizard2#23]
### Issue type
Select all that apply
- [ ] Bug
- [x] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description

I'm trying to get the list of available wifi networks but I'm not getting anything. This is the code I'm using:
```
WifiWizard2.scan(function (data) {
    alert(JSON.stringify(data));
});
```

**Expected behavior:** Should alert a JSON string of networks

**Actual behavior:** Nothing

### Versions

- Android 8.0
- WifiWizard2 3.0.0

### Additional Information

I'm running this on body load.

# EDIT
Please check [my last comment](#issuecomment-377817158)

**Comment by touficbatache** [comment]
I'm debugging the app and it seems like `WifiWizard2 is not defined` in the `cordova.js` file. Any ideas on this?

**Comment by touficbatache** [comment]
Ok, I made it work but after the following:
- Added the script directly like so: `<script src="plugins/wifiwizard2/www/WifiWizard2.js"></script>`
- Changed the code to this:
```
WifiWizard2.scan().then( function( results ){
    console.log( 'Found networks', results );
})
```

The `readme.md` file doesn't help at all when it comes to using this plugin. Please add an example to each function, it would be very very helpful! Thanks!

**Comment by touficbatache** [comment]
Ok, so to wrap everything up, add the following script in your js file like so:
```
document.addEventListener("deviceready", function() {
    WifiWizard2.scan().then( function( results ){
        // Whatever you want with results
        console.log(results);
    });
}, false);
```

I'd really like to see a warning in the `README` file that says that the code should be wrapped inside the `deviceready` event listener like so:
`document.addEventListener("deviceready", function() { // The code here }, false);`
and also an example for listing the wifi networks like so:
`console.log(results);`

Very good work on supporting this library! Was very happy to see it at very but a little more upset when I couldn't get it to work, so that's why I suggested adding examples to your `README `file.

**Comment by tripflex** [comment]
@touficbatache there is a link to a complete demo meteor project using this library, the 3.0.0 branch readme is completely different from master branch (ill be merging it soon since it appears 3.0.0 may be more stable now than the original one).

And yes, you're correct, you can't run any Cordova related API calls until `deviceready`, this is true for anything Cordova related:
https://cordova.apache.org/docs/en/latest/cordova/events/events.html#deviceready

i guess if you're trying to immediately invoke on the page loading (which I personally don't really ever do, it's always triggered by some kind action in the app), but I will add something in the readme stating this
